### ISSUE TITLE
v1 API doesn't work anymore

### ISSUE THREAD

**Issue by mrousavy** [wcandillon/react-native-redash#334] opened 2020-09-08 16:46 UTC
Hi @wcandillon !

I see you've changed master to point at the v2 API. I've upgraded to package version `15.0.2` and can't use the API at all anymore:

![Simulator Screen Shot - iPhone 11 - 2020-09-08 at 18 44 51](https://user-images.githubusercontent.com/15199031/92504860-85183000-f203-11ea-83b1-8f0cb35f29e5.png)

I've tried:

```ts
import { usePanGestureHandler, snapPoint, min, useClock, spring } from 'react-native-redash';
```

as well as:

```ts
import { usePanGestureHandler, snapPoint, min, useClock, spring } from 'react-native-redash/lib/module/v1';
```

but nothing seems to work. Am I supposed to stay on package version `14.x.x`?

**Comment by wcandillon** [comment] 2020-09-08 17:52
Thank you Marc!
That's a blessing in disguise, I'm mixing it and the migration to v15 should be much less disruptive. Stay in touch.

**Comment by wcandillon** [comment] 2020-09-08 18:57
I had the same issue and fixed it with a fresh install. Let me know. Will publish 15.0.3 which is will have cleaner exports however

**Comment by mrousavy** [comment] 2020-09-08 22:40
Are you importing the lib with 
```ts
import { usePanGestureHandler, snapPoint, min, useClock, spring } from 'react-native-redash';
```
or
```ts
import { usePanGestureHandler, snapPoint, min, useClock, spring } from 'react-native-redash/lib/module/v1';
```
?

**Comment by varemenos** [comment] 2020-09-18 22:20
Also, how do we access to docs for v1? I'm new to reanimated an redash and don't want to migrate to v2 yet (due to it still being in alpha).

**Comment by wcandillon** [comment] 2020-09-19 05:16
I've added the link for the documentation in the Readme, it is https://wcandillon.github.io/react-native-redash-v1-docs/

**Comment by dannyhw** [comment] 2020-09-19 10:38
Sorry if this is off topic but I'm having trouble getting the types to work when i use `'react-native-redash/lib/module/v1';`, adding include: `["../../node_modules/react-native-redash/lib/typescript/v1/index.d.ts"]` isn't working because the v1 folder isn't there in the typescript folder. However if I change my imports to `react-native-redash/src/v1` it does work.

**Comment by varemenos** [comment] 2020-09-19 10:52
Likewise, when I hover over the import statement in VScode I get the following:

```
Could not find a declaration file for module 'react-native-redash/lib/module/v1'. '{PROJECT_ROOT}/node_modules/react-native-redash/lib/module/v1/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-redash` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-redash/lib/module/v1';`ts(7016)
```

I tried both 
  `"include": ["node_modules/react-native-redash/lib/typescript/v1/index.d.ts"]` and 
  `"include": ["node_modules/react-native-redash/lib/typescript/v1"]`.

```
$ tree ./node_modules/react-native-redash/lib/typescript/v1 -L 1

./node_modules/react-native-redash/lib/typescript/v1
├── AnimationRunners.d.ts
├── Animations.d.ts
├── Array.d.ts
├── Colors.d.ts
├── Coordinates.d.ts
├── Gesture.d.ts
├── Hooks.d.ts
├── Math.d.ts
├── Matrix3.d.ts
├── Matrix4.d.ts
├── ReText.d.ts
├── SVG.d.ts
├── String.d.ts
├── Transformations.d.ts
├── Transitions.d.ts
├── Vectors.d.ts
├── __tests__
├── bezier
└── index.d.ts

2 directories, 17 files
```

**Comment by wcandillon** [comment] 2020-09-19 10:57
I will investigate further, could you use v14 in the meantime? Currently, between v14 and v15 there are no differences in the v1 part.

**Comment by dannyhw** [comment] 2020-09-19 11:29
Yeah I've swapped back to 14 for now, thanks for your hard work :)

**Comment by mrousavy** [comment] 2020-09-20 09:21
Sorry for hijacking this thread for this, but @wcandillon do you not have helper functions such as `snapPoint` and `diffClamp` anymore? I've upgraded to reanimated v2 and have to rethink all of my animations... 😅

**Comment by wcandillon** [comment] 2020-09-20 09:42
snapPoint, I will definitely bring back. diffClamp might not make sense anymore because you can just clamp on `onActive`. There is now notion of `diff` anymore (except in higher order animations).

**Comment by wcandillon** [comment] 2020-09-21 06:50
Guys, I'm closing this issue as a duplicate of #344. Please let me know about your issues as I'm committed to get the reanimated v1 functions work in v15.

**Closed by wcandillon** 2020-09-21 06:50 UTC

**Comment by Awsmchrlz** [comment] 2022-12-14 04:55
Still does'nt work properly, Ive tried everying stilll getting the same error...

**Comment by Awsmchrlz** [comment] 2022-12-14 04:56
> Still does'nt work properly, Ive tried everying stilll getting the same error...

'"react-native-redash"' has no exported member 'usePanGestureHandler'

**Comment by developerdevsoni** [comment] 2024-05-27 19:54
> > Still does'nt work properly, Ive tried everying stilll getting the same error...
> 
> '"react-native-redash"' has no exported member 'usePanGestureHandler'

same problem

**Comment by galbenyosef** [comment] 2025-01-07 17:08
as for 
`"expo": "~52.0.23",
"react-native": "0.76.5",`

I'm using 
`    "react-native-redash": "^16.3.0",
`
as it seems the latest one having v1 module
