### ISSUE TITLE
ReText doesn't render unicode on Android

### ISSUE THREAD

**Issue by VincentQuillien** [wcandillon/react-native-redash#417] opened 2021-01-12 16:10 UTC
Hi !

It seems ReText cannot render unicode characters on Android, I've tried both device and simulator and with different fonts.

```tsx
const text = useSharedValue('Beautiful Zürich Switzerland');

return <ReText text={text} />;
```
![Screenshot_1610467365](https://user-images.githubusercontent.com/22659282/104339644-1c65fa80-54f8-11eb-8573-487af80cedd2.png)
Works fine on iOS.

**Comment by wcandillon** [comment] 2021-01-17 08:02
Oh no 😅
Would https://github.com/axelra-ag/react-native-animateable-text be a suitable alternative for now? (cc @JonnyBurger)

**Comment by VincentQuillien** [comment] 2021-01-20 09:20
Yes I'll replace my instances of ReText with AnimateableText, thanks @JonnyBurger !

**Comment by Iltimirov** [comment] 2021-02-25 17:39
It's pity, but neither retext or animateable-text do not work with Russian symbols :(

I've tried it only in android emulator
animateable-text 0.5.9

```javascript
const animatedText = useDerivedValue(
  () => `использовать ${value.value} бонусов test`,
)
const animatedProps = useAnimatedProps(() => {
  return {
    text: animatedText.value,
  }
})
```

<img width="418" alt="Снимок экрана 2021-02-25 в 21 30 53" src="https://user-images.githubusercontent.com/15367096/109193037-64dc2d80-77b1-11eb-90fa-05dc411ad832.png">

**Comment by JonnyBurger** [comment] 2021-03-03 13:49
I think this is a bug in Reanimated (or even RN possibly). I have opened an issue here: https://github.com/software-mansion/react-native-reanimated/issues/1782

The issue is also reproducible without ReText and also happens in my react-native-animteable-text component.

However, I have found a workaround: It works if you don't wrap the text in a shared value and use it in `useAnimatedProps` directly.

Notice how in the following example one way works and one don't. If you rearchitect it a bit I'm sure you can make it work.

```tsx
import React from 'react';
import {TextInput} from 'react-native';
import Animated, {
  useAnimatedProps,
  useSharedValue,
} from 'react-native-reanimated';

const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);

const value = 'ööö';

export const Repro = () => {
  const sharedValue = useSharedValue(value);
  const animatedProps = useAnimatedProps(() => {
    return {value: `${value} ${sharedValue.value}`};
  }, []);
  return <AnimatedTextInput animatedProps={animatedProps} />;
};

// Result: ööö Ã¶Ã¶Ã¶
```

I think this issue can be closed as there is nothing that can be done in this repo.

**Comment by piaskowyk** [comment] 2021-03-04 10:31
We have PR ready to merge fix in Reanimated: https://github.com/software-mansion/react-native-reanimated/pull/1784

**Comment by Stevemoretz** [comment] 2021-04-05 15:19
Looks like it is merged?

**Comment by JonnyBurger** [comment] 2021-04-05 16:55
Yes, fixed in newest Reanimated version 👍🏼 one to close @wcandillon 🙌🏼

**Closed** 2021-04-05 17:55 UTC
